name: Render Video
on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f525247833781747dbccbd
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Render
        run: npx remotion render src/remotion/index.ts out/video.mp4

      - name: Upload
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        with:
          name: almutanabbi-video
          path: out/video.mp4
